[workspace]
authors = ["atleer <atle.rimehaug@gmail.com>"]
channels = ["conda-forge"]
name = "DL-demos"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
pytorch = ">=2.7.1,<3"
numpy = ">=2.3.2,<3"
matplotlib = ">=3.10.5,<4"
pandas = ">=2.3.1,<3"
ipykernel = ">=6.30.1,<7"
pip = ">=25.2,<26"
