---
title: "How to use PyTorch"
description: "Lots of similarities to numpy arrays."
subtitle: "2: Pytorch Basics"
engine: Jupyter
#jupyter: pytorch
title-block-banner: true
freeze: auto

execute:
    eval: true

author:
  - name: "Dr. Atle E. Rimehaug"

format:
  html: default
  ipynb: default
format-links: false
---

## Setup

### Import Libraries
```{python}
import torch
```

## Section 1: What's a tensor?

| Code | Description |
| --- | --- |
| `torch.tensor(2)` | Creates a tensor containing the scalar value 2. |
| `torch.tensor([0,1,2])` | Creates a tensor containing the vector with values 0, 1, and 2. |
| `torch.tensor([[1,2,3], [4,5,6]])` | Creates a 2-dimensional tensor of size 2x3 containing the values from 1 to 6.|

::: {#exm-}
Create a tensor of the scalar value 10.
:::

```{python}
torch.tensor(10)
```

## Section 2: Initialize Tensors

| Code | Description |
| --- | --- |
| `torch.linspace(0,5,11)` | Initializes a 1D tensor with the numbers from 0 to 5 with 0.5 spacing. |

## Section 3: Do Arithmetic Operations on Tensors

| Code | Description |
| --- | --- |
| `torch.matmul(A,B)` | Performs matrix multiplication on the two tensors A and B. |

::: {#exm-}
Perform matrix multiplication on the two tensors A and B.
:::

```{python}
A = torch.tensor([[1,2], [3,4], [5,6]])
B = torch.tensor([[7,8,9], [10,11,12]])
torch.matmul(A,B)
```

## Section 4: Convert Tensors to Other Python Objects and Set the Device

| Code | Description |
| --- | --- |
| `x = torch.tensor(2)` <br> `float(x)` | Turn torch tensor containing scalar into float number.|
| `x = torch.tensor(2.4)` <br> `x.item()` | Get value of tensor as standard Python number (the type is automatically recognized).|
| `x = torch.tensor([1, 2, 3])` <br> `x.numpy()` | Returns content of tensor as numpy array.|
::: {#exm-}
Convert the tensor object of the scalar number 5 into a float object.
:::

```{python}
x = torch.tensor([5])
float(x)
```

```{python}
x = torch.tensor([2.44, 2.1])
x = x.numpy()
x
```