---
title: "Create Neural Networks with PyTorch"
description: "Neural Networks without Object-oriented Programming"
subtitle: "4: Create Neural Networks"
engine: Jupyter
#jupyter: pytorch
title-block-banner: true
freeze: auto

execute:
    eval: true

author:
  - name: "Dr. Atle E. Rimehaug"

format:
  html: default
  ipynb: default
format-links: false
---

## Setup

### Import Libraries
```{python}
import torch
from torch import nn

from sklearn.datasets import make_moons
import pandas as pd
import matplotlib.pyplot as plt
```

### Generate Data

```{python}
X, y = make_moons(256, noise=0.1)

df = pd.DataFrame({'x0': X[:, 0], 'x1': X[:,1], 'y': y})
# Create 2D numpy array from x0 and x1 columns
X_orig = df[['x0', 'x1']].to_numpy()

# Create a 1D numpy array from the y column
y_orig = df['y'].to_numpy()

plt.scatter(X_orig[:,0], X_orig[:,1], s = 40, c=y_orig)
```

```{python}
# Convert the 2D points to a tensor
X = torch.tensor(X_orig, dtype = torch.float32)

# Convert labels to long integer tensor
y = torch.from_numpy(y_orig).type(torch.LongTensor)
```

## Section 1: Create Layers of Neurons and Pass Input to It

| Code | Description |
| --- | --- |
| `nn.Linear(n_features_in, n_features_out)` | Creates a single layer of neurons that takes in `n_features_in` input features and outputs `n_features_out` features.|
| `nn.ReLU()` | Creates a rectified linear unit activation function.|
| `nn.Tanh()` | Creates a hyperbolic tangent activation function.|
| `nn.Softmax()` | Creates a softmax activation function.|
| `nn.Sequential(nn.Linear(1,10),`<br>&nbsp;&nbsp;&nbsp;&nbsp;` nn.ReLU(),`<br>&nbsp;&nbsp;&nbsp;` nn.Linear(10,1)`<br>`)` | Creates a container where layers and activation functions are stacked in a sequential order and ensures that the input is passed through the network in that order.|

::: {#exm-}
Create a single layer of 16 neurons that takes in two features.
:::

```{python}
nn.Linear(2, 16)
```

::: {#exr-}
Create a single layer of 8 neurons that takes in one feature.
:::

::: {#sol-}
:::
```{python}
nn.Linear(1,8)
```

::: {#exr-}
Create a single layer of 10 neurons that takes in 15 features.
:::

::: {#sol-}
:::
```{python}
nn.Linear(15,10)
```

::: {#exr-}
Create a rectified linear unit activation function.
:::

::: {#sol-}
:::
```{python}
nn.ReLU()
```

::: {#exr-}
Create a hyperbolic tangent activation function.
:::

::: {#sol-}
:::
```{python}
nn.Tanh()
```
::: {#exr-}
Create a softmax activation function.
:::

::: {#sol-}
:::
```{python}
nn.Softmax()
```

::: {#exr-}
Create a sequence of layers with a rectified linear unit between them. The first layer should take two input features, and consist of 16 neurons, the second layer should take in the 16 outputs from the previous layer and output two features.
When you display it, the output should look like this:

Sequential(  <br>
  &nbsp;&nbsp;(0): Linear(in_features=2, out_features=16, bias=True)  <br>
  &nbsp;&nbsp;(1): ReLU()  <br>
  &nbsp;&nbsp;(2): Linear(in_features=16, out_features=2, bias=True)  <br>
)
:::

::: {#sol-}
:::
```{python}
nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,2)
)
```

::: {#exr-}
Create a sequence of layers with a tanh activation between them and a **softmax** activation function after the last layer. The number of input and output features in each layer should be the same as in the previous exercise. Display it to see that you've constructed it correctly.
:::

```{python}
nn.Sequential(
  nn.Linear(4, 16),
  nn.Tanh(),
  nn.Linear(16,4),
  nn.Softmax()
)
```

::: {#exr-}
Create a variable `net` that contains the sequence of layers and activation functions defined in **exercise 5**

```{python}
net = nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,2)
)
```

Pass the input ``X_samples``  to the net. When you display the output it should look something like this:
:::

tensor([[0.2487, 0.4821],  <br>
&nbsp;[0.4219, 0.5308],  <br>
&nbsp;[0.1854, 0.3364],  <br>
&nbsp;[0.5181, 0.5929],  <br>
&nbsp;[0.9043, 0.9941]], grad_fn=``<AddmmBackward0>``)

::: {#sol-}
:::
```{python}
X_samples = X[:5]

net(X_samples)
```

## Section 2: The Loss Function and the Optimizer

| Code | Description |
| --- | --- |
| `loss_function = nn.MSELoss()` | Creates a mean squared error (MSE) loss function and assigns it to a variable named `loss_function`. Typically used for regression problems. |
| `nn.CrossEntropyLoss()` | Creates a cross-entropy loss function. Used for classification problems.|
| `nn.NLLLoss()` | Creates a negative log-likelihood loss function. Used for classification problems. Expects different input format than cross-entropy loss. |
| `loss_function(y_net, y_true)` | Calculates the loss between the y-values given as output by the network `y_net` and the true y-values from the data `y_true`. |
| `optim.SGD(net.parameters(), lr=0.01, momentum = 0.99)` | Creates a stochastic gradient descent (GD) optimizer with a learning rate `lr` of 0.01 (the default value is 0.001) and ``momentum`` of 0.99 (the default value is 0.9). |
| `optim.Adagrad(net.parameters())` | Creates an adaptive gradient descent optimizer.|
| `optim.ADAM(net.parameters())` | Creates an adaptive moment optimizer .|


::: {#exm-}
Create a negative log-likelihood loss function.
:::
```{python}
nn.NLLLoss()
```

::: {#exr-}
Create a mean square error loss function.
:::

::: {#sol-}
:::
```{python}
nn.MSELoss()
```

::: {#exr-}
Create a cross-entropy loss function and assign it to a variable called `loss_function`.
:::

::: {#sol-}
:::
```{python}
loss_function = nn.CrossEntropyLoss()
loss_function
```

::: {#exr-}
Calculate the loss between the output (`y_net`) produced by the neural net in the cell below and the original y-data (`y_samples`).
:::

```{python}
# create net
net = nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,2)
)

# select subset of data
X_samples = X[:100]
y_samples = y[:100]

# 
y_net = net(X_samples)
```
::: {#sol-}
:::
```{python}
loss_function(y_net, y_samples)
```

::: {#exr-}
Create a gradient descent optimizer.
:::

::: {#sol-}
:::
```{python}
optimizer = torch.optim.SGD(net.parameters())
optimizer
```

::: {#exr-}
Create an adaptive gradient (Adagrad) optimize.
:::

::: {#sol-}
:::
```{python}
optimizer = torch.optim.Adagrad(net.parameters())
optimizer
```

::: {#exr-}
Create an adaptive moment (Adam) optimizer with learning rate ``lr = 0.01``.
:::

::: {#sol-}
:::
```{python}
optimizer = torch.optim.Adam(net.parameters(), lr=0.01)
optimizer
```

::: {#exr-}
Create a gradient descent optimizer with `momentum = 0.95` and learning rate `lr = 0.01`.
:::

::: {#sol-}
:::
```{python}
optimizer = torch.optim.SGD(net.parameters(), lr = 0.01, momentum=0.95)
optimizer
```

## Section 3: Calculate the Accuracy

| Code | Description |
| --- | --- |
| `a == b` | Compares each element of the tensors (or arrays) `a` and `b` and returns a tensor of boolean (`True` or `False`) values indicating which elements are the same (`True`) and different (`False`). |
| `(a == b).sum()` or `torch.sum(a == b)`| Sums all elements where the condition `a == b` is `True`. `True` is counted as 1, `False` as 0. |
| `(a == b).sum() / len(a)` | Calculates proportion of elements in `a` where the element is equal to the corresponding element in `b`.|

Run the cell below to create a network, select a subset of the data, and pass this subset through the network to get an output `y_net`.

```{python}
net = nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,2)
)

# select subset of data
X_samples = X[:200]
y_samples = y[:200]

y_net = net(X_samples)
```

The output of the network is a score for each class that reflects the networks belief that a data point corresponds to a given class. This is not the same as a class label, so to get the output in the form of a class guess by the network, we have to determine which class the network thinks that a data point is most likely to belong to using the outputted scores.

::: {#exr-}
Find the column index (which corresponds to the class label) at which the score is highest for every data point. *Hint*: torch's argmax function may be useful here. If you display the result it should be a tensor containing only 1's and 0's.
:::

::: {#sol-}
:::
```{python}
y_pred = torch.argmax(y_net, dim=1)
y_pred
```

::: {#exr-}
Now, the network prediction can be compared directly with the true labels from the data. Check how many of the network predicted classes match the true labels.
:::

::: {#sol-}
:::
```{python}
(y_pred == y_samples).sum()
```

::: {#exr-}
Divide the total number of matches by the total number of data points in the sample. This should be a number between 0 and 1 and is the accuracy of the network prediction.
:::

```{python}
accuracy = (y_pred == y_samples).sum()/len(y_samples)
accuracy
```

## Section 4: Train the Network

| Code | Description |
| --- | --- |
| `optimizer.zero_grad()` | Zero out gradients. |
| `loss.backward()` | Do backpropagation. |
| `optimizer.step()` | Update parameters of network using gradients calculated during backpropagation. |

Run the cell below to define a network, select a subset of the data, and define an optimizer.

```{python}
net = nn.Sequential(
    nn.Linear(2,16),
    nn.ReLU(),
    nn.Linear(16,2)
)

# select subset of data
X_samples = X[:200]
y_samples = y[:200]

optimizer = torch.optim.Adam(net.parameters(), lr=0.01)
```


::: {#exr-}
Set the gradients to zero for the optimizer defined above. This is necessary to avoid that  gradients accumulate over successive iterations during training. The gradients should only be calculated from the loss in the current iteration.
:::

::: {#sol-}
:::
```{python}
optimizer.zero_grad()
```


::: {#exr-}
In the cell below, the loss is calculated for the output of the network after passing `X_samples` as input to it. Do backpropagation on the computed loss. This calculates the gradients for this iteration.
:::

```{python}
loss_function = nn.CrossEntropyLoss()

output = net(X_samples)

loss = loss_function(output, y_samples)
print(loss.item())
```

::: {#sol-}
:::
```{python}
loss.backward()
```

::: {#exr-}
Update the parameters of the network.
:::

```{python}
optimizer.step()
```

::: {#exr-}
Pass `X_samples` as input to the network again and calculate and print the loss anew for this output. Compare to the loss printed in the first exercise of this section. Is it different? If so, what does that suggest?
:::

::: {#sol-}
:::
```{python}
output = net(X_samples)

loss = loss_function(output, y_samples)
print(loss.item())
```

